# Generated by Django 6.0.3 on 2026-04-02 15:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SimulationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='running', max_length=20)),
                ('input_payload', models.JSONField(default=dict)),
                ('mean_yield', models.FloatField(blank=True, null=True)),
                ('std_yield', models.FloatField(blank=True, null=True)),
                ('best_yield', models.FloatField(blank=True, null=True)),
                ('worst_yield', models.FloatField(blank=True, null=True)),
                ('total_dies', models.IntegerField(blank=True, null=True)),
                ('result_payload', models.JSONField(blank=True, default=dict)),
                ('wafer_map_image', models.ImageField(blank=True, null=True, upload_to='simulation_runs/')),
                ('pareto_image', models.ImageField(blank=True, null=True, upload_to='simulation_runs/')),
                ('error_message', models.TextField(blank=True, default='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simulation_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
